/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_com_galleonlabs_nativetest_NativeLib */

#ifndef _Included_com_example_com_galleonlabs_nativetest_NativeLib
#define _Included_com_example_com_galleonlabs_nativetest_NativeLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_com_galleonlabs_nativetest_NativeLib
 * Method:    addTwoNative
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_com_example_com_galleonlabs_nativetest_NativeLib_addTwoNative
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
